name: War
description: War is a command and conquer style game.

version: 1.0.0
author: Mark Tanner <admin@64bitdragon.com>
homepage: https://github.com/marktanner1331/war

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  stagexl: ^1.1.0
  stagexl_ui_components:
    git: https://github.com/marktanner1331/stagexl_ui_components
